name: Haddock

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache Stack
      id: cache-stack-unix
      uses: actions/cache@v3
      with:
        path: ~/.stack
        key: ubuntu-latest-stack-home-${{ hashFiles('stack.yaml') }}-${{ hashFiles('package.yaml') }}
        
    - name: Setup stack
      uses: haskell/actions/setup@v1
      with:
        enable-stack: true
        stack-no-global: true

    - name: Build Haddock
      run: |
        stack haddock --haddock-arguments "--odir docs"

    - name: Deploy to GitHub Pages
      uses: Cecilapp/GitHub-Pages-deploy@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        build_dir: docs
